### PR TITLE
Added ghcjs support.

### LINKED ISSUE #40: GHCJs support
Would you consider a PR for some additional CPP for using https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues. At a glance the apis look compatible and this is the best way to get entropy in a browser from my experience.

I'm happy to put the work in to do it. 

It would help things like: https://github.com/haskell-hvr/uuid/issues/37

### PR DESCRIPTION
**Pull request by eskimor**
Fixes #40 .

### CODE REVIEW

**Comment by TomMD** [comment]
This looks straight forward, though not being a ghcjs user I can't test it.  Do you consider this ready for release @eskimor?  @benkolera do you have any comments to add here since you reported issue #40?

Thanks for the PR!

**Comment by eskimor** [comment]
I have a ghcjs application running already based on this PR, so I can definitely say it works. The only issue I can think of is, if there are people compiling with ghcjs but for node instead of the browser it might not work, as browser APIs might not be available. On the other hand, the ghc version would most likely not work in this case either, so this PR should not make matters worse.

The other thing is, I was not able to test whether I broke some other platform. I tested ghc on Linux, but I don't have Windows box for example. Other than those points, I would say - yeah ready for release :-)

**Comment by benkolera** [comment]
LGTM. Thanks @eskimor !

**Comment by benkolera** [comment]
I gave this a good test in an obelisk project which both runs in GHC and GHCJs depending on the build target. Works well. 

It is probably worth changing the haddock at the top of System.Entropy to include GHCJs, though! :slightly_smiling_face: 

https://github.com/TomMD/entropy/blob/f3a5b285efd2c9a3eecf2b307d3e9b66a8aec384/System/Entropy.hs#L9-L15

**Comment by eskimor** [comment]
Thanks for testing - and good catch!

**Comment by TomMD** [comment]
Excellent, thanks for the effort everyone.

**Pull request merged**
