### PR TITLE
fix macro name error

### LINKED ISSUE #75: build error
## Error Info
```
cbits/random_initialized.c:9:9: error:
     error: macro names must be identifiers
        9 | #ifndef !DO_NOT_USE_GET_ENTROPY
          |         ^
  |
9 | #ifndef !DO_NOT_USE_GET_ENTROPY
  |         ^
cbits/random_initialized.c: In function ‘ensure_pool_initialized’:

cbits/random_initialized.c:51:9: error:
     error: macro names must be identifiers
       51 | #ifndef !DO_NOT_USE_GET_ENTROPY
          |         ^
   |
51 | #ifndef !DO_NOT_USE_GET_ENTROPY
   |         ^
`gcc' failed in phase `C Compiler'. (Exit code: 1)

```
## Env
- ghc: 8.10.7
- os: ubuntu 20.04
- gcc: 10.3.0

### PR DESCRIPTION
**Pull request by daleiz**
fix #75

### CODE REVIEW

**Comment by tchoutri** [comment]
I just stumbled on this error whilst migrating [flora](https://github.com/flora-pm/flora-server) to GHC 9.2. Thank you @daleiz

**Comment by tfausak** [comment]
@TomMD could you take a look at this? I have many builds failing with `entropy-0.4.1.9` and I'll bet other people are in the same boat.

**Comment by TomMD** [comment]
*sigh* What did I do? Well at least I know there are users.  Gees Tom.

**Comment by tfausak** [comment]
No problem at all! Things happen :) 

I can confirm that `entropy-0.4.1.10` built successfully for me. Thanks!

**Comment by tchoutri** [comment]
@TomMD Thanks a lot for the release, I can confirm every is good on my side! (And take care of yourself :heart:)

**Pull request merged**
