### PR TITLE
bump Cabal upper bound to < 3.9

### PR DESCRIPTION
**Pull request by mitchellwrosen**

### CODE REVIEW

**Comment by ysangkok** [comment]
Wouldn't it be better to just remove the bound? In the optimistic case where Cabal doesn't break compat in the future, we'd avoid having to do PRs like this.

**Comment by mitchellwrosen** [comment]
Not if you ask me. Missing upper bounds on old versions of a library poison build plans unless a revision is made, which a library author is not likely to remember to do. 

But that's probably not a debate to be had on this random ticket; I think the author/maintainer can do whatever they want with this PR.

**Comment by phadej** [comment]
Looks like `entropy` doesn't work with GHC-9.4 and windows (due toolchain change from gcc to clang). So it's possible that a release is needed (and revisions to existing releases).

**Comment by phadej** [comment]
Correction to previous, build failures I was seeing with GHC-9.4 came from compiling older `entropy` versions. Relaxing this bound seems to work https://github.com/phadej/entropy/actions/runs/2859399288 https://github.com/TomMD/entropy/compare/master...phadej:entropy:simple-ci and linking works, but also without updating bounds.

**Comment by phadej** [comment]
I made a revision allowing `Cabal-3.8` (https://hackage.haskell.org/package/entropy-0.4.1.7/revisions/) as I was making revision for #72 anyway.

**Comment by TomMD** [comment]
Much appreciated!

**Pull request merged**
